const express = require('express');
const connectDB = require('./src/config/database');
const playerRoutes = require('./src/routes/playerRoutes');
const tournamentRoutes = require('./src/routes/tournamentRoutes');
// const setupSwagger = require('./swagger'); // <--- REMOVE OR COMMENT OUT THIS LINE
const swaggerUi = require('swagger-ui-express'); // <--- ADD THIS LINE
const swaggerFile = require('./swagger-output.json'); // <--- ADD THIS LINE to import the generated JSON

const app = express();
const PORT = process.env.PORT || 5500;

// Middleware
app.use(express.json());

// Connect to MongoDB
connectDB();

// Setup Swagger UI to serve the autogenerated documentation
// setupSwagger(app); // <--- REMOVE OR COMMENT OUT THIS LINE
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerFile)); // <--- ADD THIS LINE

// Routes
app.use('/api/players', playerRoutes);
app.use('/api/tournaments', tournamentRoutes);

// Start the server
app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});